GET http://localhost:3000/products/d2ff3048-83bc-425a-8ad3-d6d9af1c7c6d

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "코드잇 후디",
  "description": "코드잇 로고가 새겨진 보라색 후디.",
  "category": "FASHION",
  "price": 39000,
  "stock": 30
}

###

PATCH http://localhost:3000/products/f8013040-b076-4dc4-8677-11be9a17162f
Content-Type: application/json

{
  "price": 40000,
  "stock": 19
}
###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": "70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45",
  "orderItems": [
    {
      "productId": "1e112c02-7c92-4d52-b76e-485e41e3f64d",
      "unitPrice": 59000,
      "quantity": 1
    },
    {
      "productId": "f751e63f-686d-42d4-898e-3ef6d4137908",
      "unitPrice": 79000,
      "quantity": 2
    }
  ]
}
###
GET http://localhost:3000/products/1e112c02-7c92-4d52-b76e-485e41e3f64d

###

GET http://localhost:3000/products/f751e63f-686d-42d4-898e-3ef6d4137908
